In [1]:
import numpy as np
import astropy.units as u

### Qn 1.

In [2]:
gratings = np.array([400, 700, 1200]) # grooves per mm
h_alpha = 656.3 * u.nm
d_vals = (1/gratings * u.mm).to(u.m)


In [3]:
def get_blaze_angle(d, l):
    return np.arcsin(l / (2 * d)) # For 1st order
blaze_angle = get_blaze_angle(d_vals, h_alpha)
print(blaze_angle.to(u.deg))

[ 7.54240896 13.27970449 23.18990749] deg


### Qn 2.

In [4]:
slit_size = (1*u.arcsec).to(u.rad)
D_tel = 6.5 * u.m
D_beam = (150 * u.mm).to(u.m)

def get_resolving_power(D_tel, D_beam, slit_size, blaze_angle):
    return (2*np.tan(blaze_angle)/ slit_size)* (D_beam / D_tel) 
resolving_power = get_resolving_power(D_tel, D_beam, slit_size, blaze_angle)
print(resolving_power)

[1260.48971472 2246.85202368 4078.25560388] 1 / rad


### Qn 3. 

#### Answer: Doubling the beam size will double the resolving power.

### Qn 4.

In [5]:
resolving_power = get_resolving_power(D_tel, 2*D_beam, slit_size, blaze_angle)  # 2x beam diameter
print(resolving_power)

[2520.97942945 4493.70404736 8156.51120776] 1 / rad


### Qn 5.
#### Answer: When you double the beam size, you will need a bigger camera/spectrograph to capture the light.

### Qn 6.

In [6]:
def get_vals(focal_length, D_tel, ):
    f_ratio = focal_length / D_tel

    print(f"f-ratio: {f_ratio}")

In [7]:
focal_length = 0.115 * u.m # Focal length of the Camera
D_tel = 2*(150/1000 * u.m) # Beam diameter <= Camera diameter
get_vals(focal_length, D_tel)

f-ratio: 0.38333333333333336


### Qn 7.

In [8]:
# Original Design
# Assuming camera diameter at 150mm
D_tel = (150 * u.mm).to(u.m) # Beam diameter <= Camera diameter

# Length = collimator focal length + camera focal length
focal_length = 0.115 * u.m
camera_focal_length = 0.115 * u.m # Since Diameters are same

# Spectrograph length
length = focal_length + camera_focal_length
print('Spectrograph Length:',length)

# Assuming a cylinder, the volume of the spectrograph is
def get_volume(D_tel, length):
    return np.pi * (D_tel/2)**2 * length
volume_1 = get_volume(D_tel, length)
print('Volume:',volume_1)

Spectrograph Length: 0.23 m
Volume: 0.004064435495581795 m3


In [9]:
# New Design
# Assuming camera diameter at 300mm
D_tel = (300 * u.mm).to(u.m) # Beam diameter <= Camera diameter

# Volume of the spectrograph
volume_2 = get_volume(D_tel, length)
print('Volume:',volume_2)

# Ratio of the volumes
print('Volume Ratio:',volume_2/volume_1)

Volume: 0.01625774198232718 m3
Volume Ratio: 4.0


#### Assuming the density is constant, the new design will be 4 times heavier than the original design

### Qn 8.

#### Answer: The optical design is sound. The biggest challenge would be structural stability and alignment of the optics. 
#### Since the spectrograph is now larger and more massive.